development:
  adapter: mysql2
  database: registry_dev
  encoding: utf8
  username: root
  password: developer
  host: localhost

test: &test
  adapter: mysql2
  database: registry_test
  encoding: utf8
  username: root
  password: developer
  host: localhost
